name = "Jamm Trade Admin"
client_id = "b63704e1c1dc653a6f024f499086b46c"
application_url = "https://www.jammtrade.com"
embedded = false


[auth]
redirect_urls = [
  "https://www.jammtrade.com/api/auth/shopify/callback",
  "http://localhost:3456/callback"
]

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = [ "shop/update" ]
uri = "https://www.jammtrade.com/api/webhooks/shopify/shop-update"
